version: "3.8"

services:
  # Base Edge Service
  edge:
    build: ./edge
    networks:
      cdn_network:
        # Providing a default alias (if needed by a template)
        aliases:
          - edge
    volumes:   
      - ./edge/html:/usr/share/nginx/html # Correctly map the HTML directory
      - ./edge/nginx.conf:/etc/nginx/conf.d/default.conf # Map the NGINX configuration file

  # Edge servers in the US
  edge_us_1:
    extends:
      service: edge
    networks:
      cdn_network:
        aliases:
          - edge_us_1
  edge_us_2:
    extends:
      service: edge
    networks:
      cdn_network:
        aliases:
          - edge_us_2
  edge_us_3:
    extends:
      service: edge
    networks:
      cdn_network:
        aliases:
          - edge_us_3

  # Edge servers in Europe
  edge_eu_1:
    extends:
      service: edge
    networks:
      cdn_network:
        aliases:
          - edge_eu_1
  edge_eu_2:
    extends:
      service: edge
    networks:
      cdn_network:
        aliases:
          - edge_eu_2
  edge_eu_3:
    extends:
      service: edge
    networks:
      cdn_network:
        aliases:
          - edge_eu_3

  # Edge servers in Asia
  edge_asia_1:
    extends:
      service: edge
    networks:
      cdn_network:
        aliases:
          - edge_asia_1
  edge_asia_2:
    extends:
      service: edge
    networks:
      cdn_network:
        aliases:
          - edge_asia_2
  edge_asia_3:
    extends:
      service: edge
    networks:
      cdn_network:
        aliases:
          - edge_asia_3

  # Edge servers in South America
  edge_sa_1:
    extends:
      service: edge
    networks:
      cdn_network:
        aliases:
          - edge_sa_1
  edge_sa_2:
    extends:
      service: edge
    networks:
      cdn_network:
        aliases:
          - edge_sa_2
  edge_sa_3:
    extends:
      service: edge
    networks:
      cdn_network:
        aliases:
          - edge_sa_3

  # Edge servers in Australia
  edge_au_1:
    extends:
      service: edge
    networks:
      cdn_network:
        aliases:
          - edge_au_1
  edge_au_2:
    extends:
      service: edge
    networks:
      cdn_network:
        aliases:
          - edge_au_2
  edge_au_3:
    extends:
      service: edge
    networks:
      cdn_network:
        aliases:
          - edge_au_3

  # Regional Load Balancers
  region_us:
    build:
      context: ./regions
      args:
        REGION: "us"
    ports:
      - "8081:80"
    depends_on:
      - edge_us_1
      - edge_us_2
      - edge_us_3
    networks:
      - cdn_network

  region_eu:
    build:
      context: ./regions
      args:
        REGION: "eu"
    ports:
      - "8082:80"
    depends_on:
      - edge_eu_1
      - edge_eu_2
      - edge_eu_3
    networks:
      - cdn_network

  region_asia:
    build:
      context: ./regions
      args:
        REGION: "asia"
    ports:
      - "8083:80"
    depends_on:
      - edge_asia_1
      - edge_asia_2
      - edge_asia_3
    networks:
      - cdn_network

  # Regional Load Balancer for South America
  region_sa:
    build:
      context: ./regions
      args:
        REGION: "sa"
    ports:
      - "8084:80"
    depends_on:
      - edge_sa_1
      - edge_sa_2
      - edge_sa_3
    networks:
      - cdn_network

  # Regional Load Balancer for Australia
  region_au:
    build:
      context: ./regions
      args:
        REGION: "au"
    ports:
      - "8085:80"
    depends_on:
      - edge_au_1
      - edge_au_2
      - edge_au_3
    networks:
      - cdn_network

  # Global Routing Server
  global_router:
    build: ./global
    depends_on:
      - region_us
      - region_eu
      - region_asia
      - region_sa
    ports:
      - "8080:80"
    volumes:
      - ./global/geoip:/etc/nginx/geoip # Map the GeoIP database
      - ./global/nginx.conf:/etc/nginx/nginx.conf # Map the global NGINX configuration
    networks:
      - cdn_network

  termination_detector:
    build:
      context: ./scripts
    privileged: true
    volumes:
      - ./scripts/termination_detector.sh:/termination_detector.sh
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: ["bash", "/termination_detector.sh"]
    depends_on:
      - global_router
      - region_us
      - region_eu
      - region_asia
      - region_sa
      - edge_us_1
      - edge_us_2
      - edge_us_3
      - edge_eu_1
      - edge_eu_2
      - edge_eu_3
      - edge_asia_1
      - edge_asia_2
      - edge_asia_3
      - edge_sa_1
      - edge_sa_2
      - edge_sa_3
    networks:
      - cdn_network

  # Retain snapshot_collector
  snapshot_collector:
    build:
      context: ./scripts
    privileged: true
    volumes:
      - ./scripts/chandy_lamport_snapshot.sh:/chandy_lamport_snapshot.sh
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: ["bash", "/chandy_lamport_snapshot.sh"]
    depends_on:
      - global_router
      - region_us
      - region_eu
      - region_asia
      - region_sa
      - edge_us_1
      - edge_us_2
      - edge_us_3
      - edge_eu_1
      - edge_eu_2
      - edge_eu_3
      - edge_asia_1
      - edge_asia_2
      - edge_asia_3
      - edge_sa_1
      - edge_sa_2
      - edge_sa_3
    networks:
      - cdn_network

  # Retain deadlock_detector
  deadlock_detector:
    build:
      context: ./scripts
    privileged: true
    volumes:
      - ./scripts/deadlock_detector.sh:/deadlock_detector.sh
      - /var/run/docker.sock:/var/run/docker.sock # Mount Docker socket
    entrypoint: ["bash", "/deadlock_detector.sh"]
    depends_on:
      - global_router
      - region_us
      - region_eu
      - region_asia
      - region_sa
      - edge_us_1
      - edge_us_2
      - edge_us_3
      - edge_eu_1
      - edge_eu_2
      - edge_eu_3
      - edge_asia_1
      - edge_asia_2
      - edge_asia_3
      - edge_sa_1
      - edge_sa_2
      - edge_sa_3
    networks:
      - cdn_network

  snapshot_termination_detector:
    build:
      context: ./scripts
    privileged: true
    volumes:
      - ./scripts/snapshot_based_termination_detector.sh:/snapshot_based_termination_detector.sh
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: ["bash", "/snapshot_based_termination_detector.sh"]
    depends_on:
      - global_router
      - region_us
      - region_eu
      - region_asia
      - region_sa
      - edge_us_1
      - edge_us_2
      - edge_us_3
      - edge_eu_1
      - edge_eu_2
      - edge_eu_3
      - edge_asia_1
      - edge_asia_2
      - edge_asia_3
      - edge_sa_1
      - edge_sa_2
      - edge_sa_3
    networks:
      - cdn_network

networks:
  cdn_network:
    driver: bridge
